# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0570e4d3a7855d38f5e17d114f655452245c2bbd35145c4691be57bb1973ac629d020d7d9dec5bb4d47ccf5cba5c2351ee8ba712d24c8789efd7e3ffaa1a3735

test:
  secret_key_base: 25eaa46883870df05d8cd61b59fe698fd1690c0ee0970e649fdd45688ba0306809dfcc33d5e2458a4020b1e48f176afb440c8fe3d7d9c8ef0e7691e4887cd053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
